POST http://localhost:8081/api/user/signup HTTP/1.1
content-type: application/json

{
    "email": "testuser5@test.com",
    "password": "testing123"
}

###

POST http://localhost:8081/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

###
